# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-20 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(max_length=50, verbose_name='课程描述')),
                ('detail', models.TextField(verbose_name='课程细节')),
                ('degree', models.CharField(choices=[('hard', '难'), ('middle', '普通'), ('easy', '简单')], max_length=6)),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('image', models.ImageField(upload_to='Courses/%Y/%m', verbose_name='封面图片')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(default='后端', max_length=20, verbose_name='类别')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='标签')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否是轮播图')),
                ('course_tag', models.CharField(default='全国知名', max_length=8, verbose_name='课程标签')),
                ('price', models.IntegerField(verbose_name='课程价格')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构')),
            ],
            options={
                'verbose_name': '课程名',
                'verbose_name_plural': '课程名',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资料名')),
                ('download', models.FileField(upload_to='courses/resource/%Y/%m', verbose_name='下载')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节名',
                'verbose_name_plural': '章节名',
            },
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_know_before', models.CharField(default='', max_length=200, verbose_name='课程须知')),
                ('to_tell_you', models.CharField(default='', max_length=200, verbose_name='老师告诉你')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程教师')),
            ],
            options={
                'verbose_name': '教师课程',
                'verbose_name_plural': '教师课程',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('video_url', models.CharField(default='', max_length=200, verbose_name='视频链接')),
                ('time', models.CharField(default='', max_length=6, verbose_name='视频时长')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '视频名',
                'verbose_name_plural': '视频名',
            },
        ),
        migrations.AddField(
            model_name='courseresource',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Video', verbose_name='视频'),
        ),
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
            },
            bases=('courses.course',),
        ),
    ]
